a=raw_input("Enter petrol in bike")
b=raw_input("Enter travlled in KM")
c=raw_input("Enter millage km/hr")
d=int(a)*int(c)
print("Total km he can travlle")
f=int(d)-int(b)
print("Km more he can travvle ", f)
